version: "3.8"

services: 
    sqlserver:
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=myStrongPassword12#
        ports:
            - '1433:1433'
        volumes:
            - sqldata:/var/opt/mssql/sqlserver
        container_name: sqlserver
        image: mcr.microsoft.com/mssql/server
        deploy:
            resources:
                reservations:
                    cpus: '2'
                    memory: 2GB
                # limits:
                #     cpus: '2'
                #     memory: 2GB
                # reservations:
                #     cpus: '2'
                #     memory: 2GB
    web-app:
        ports: 
            - "80:80"
        container_name: web-app
        # build:
        #     dockerfile: ./Dockerfile
        image: dowhilecontactsscr.azurecr.io/contacts-image:v1
        # image: contacts-image
        domainname: do-while
        restart: on-failure

volumes:
    sqldata:
        # external: true
        driver: azure_file
        driver_opts:
            share_name: sql-volume
            storage_account_name: contactsstorageaccdow
